Vagrant.configure("2") do |config|

    nodes = [
      { name: "master", ip: "192.168.56.110" },
      { name: "worker", ip: "192.168.56.111" }
    ]
  
    nodes.each do |node|
      config.vm.define node[:name] do |n|
        n.vm.box = "ubuntu/focal64"
  
        n.vm.provision :docker
        n.vm.provision "shell" do |s|
          ssh_pub_key = File.readlines("keys/docker.pub").first.strip 
          s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
          sudo sed -i 's/^\\s*PasswordAuthentication\\s\\+no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart sshd.service
        SHELL
        end
        n.vm.network "private_network", ip: node[:ip]
        n.vm.hostname = node[:name]
      end
    end
  end